# Question no.1

In [57]:
import numpy as np

In [58]:
list_ = [ '1' , '2', '3' , '4' , '5' ]

In [59]:
list_

['1', '2', '3', '4', '5']

In [60]:
type(list_)

list

In [61]:
list_[0]

'1'

In [62]:
type(list_[0])   # data type of variables list_

str

In [63]:
array_list = np.array(object = list_)

In [64]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [65]:
type(array_list)

numpy.ndarray

In [66]:
array_list[0]

'1'

In [67]:
type(array_list[0]) #data type of variables array_list

numpy.str_

# Question no.2

In [68]:
type(list_[1])

str

In [72]:
for i in list_:
    print(type([i]))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [70]:
type(array_list[0])

numpy.str_

In [73]:
for i in array_list:
    print(type([i]))
    

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


# Question no. 3

In [74]:
array_list = np.array(object = list_, dtype = int)

In [75]:
array_list

array([1, 2, 3, 4, 5])

In [76]:
list_[0]

'1'

In [77]:
type(list_[0])

str

In [82]:
for i in list_:
    print(type[i])

type['1']
type['2']
type['3']
type['4']
type['5']


In [78]:
array_list[0]

1

In [79]:
type(array_list[0])

numpy.int64

In [83]:
for i in array_list:
    print(type[i])

type[1]
type[2]
type[3]
type[4]
type[5]


# Question no.4

In [84]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [85]:
num_array = np.array(object = num_list)

In [86]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
num_array.shape

(2, 3)

In [88]:
num_array.size

6

# Qutestion no.5

In [97]:
import numpy as np

In [103]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Qutetion no.6

In [106]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])